### ISSUE TITLE
configs

### ISSUE THREAD

**Issue by Maritime-Moon** [jkli1998/DRM#2]
Can you tell me the difference between the config files under the configs folder?

**Comment by jkli1998** [comment]
Most of them inherit from the library [maskrcnn](https://github.com/facebookresearch/maskrcnn-benchmark) for detection and segmentation. We only added `configs/DRM_e2e_relation_X_101_32_8_FPN_1x.yaml` for training our model.

**Comment by Maritime-Moon** [comment]
When I run the relation_train_net.py, I get an error：
E:\anaconda\envs\DRM\python.exe E:\learn_code\DRM-main\tools\relation_train_net.py 
Traceback (most recent call last):
  File "E:\learn_code\DRM-main\tools\relation_train_net.py", line 22, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\data\__init__.py", line 2, in <module>
    from .build import make_data_loader, get_dataset_statistics, make_data_infer_loader
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\data\build.py", line 13, in <module>
    from maskrcnn_benchmark.utils.miscellaneous import save_labels
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\utils\miscellaneous.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\structures\boxlist_ops.py", line 7, in <module>
    from maskrcnn_benchmark.layers import nms as _box_nms
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\layers\__init__.py", line 10, in <module>
    from .nms import nms
  File "E:\learn_code\DRM-main\maskrcnn_benchmark\layers\nms.py", line 8, in <module>
    nms = amp.float_function(_C.nms)
  File "E:\anaconda\envs\DRM\lib\site-packages\yacs\config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: nms
I looked and found that I didn't find _C.nms

**Comment by Maritime-Moon** [comment]
Can you provide information about _C.nms?

**Comment by jkli1998** [comment]
This error appears to be caused by compiling this repo uncorrectly, you need to carefully follow [INSTALL.md](https://github.com/jkli1998/DRM/blob/main/INSTALL.md) to install this code step by step, especially the last command `python setup.py build develop`.
